# 30DayChartChallenge
# 2022
# Category : Relationships
# Day 13 : Correlation
# Last updated 2022-03-14

# https://www.tylervigen.com/spurious-correlations

# Load packages ----

library(tidyverse)

# Data wrangling ----

d1 <- tibble(
  year = seq(2000, 2009, 1),
  arcade_revenue = c(1.196, 1.176, 1.269, 1.24, 1.307, 1.435, 1.601, 1.654, 1.803, 1.734),
  doctorates = c(861, 830, 809, 867, 948, 1129, 1453, 1656, 1787, 1611)) %>% 
  mutate(arcade_revenue_scaled = (arcade_revenue - 1),
         doctorates_scaled = (doctorates - 500) / 1500)

axis_ticks <- tibble(
  x = seq(1999.5, 2009.5, 1),
  y1 = 0,
  y2 = 1)

# Create plot ----

p <- ggplot() +
  geom_segment(aes(x = 1999.5, xend = 2009.5, y = 1/3, yend = 1/3), colour = "grey", size = 0.25) +
  geom_segment(aes(x = 1999.5, xend = 2009.5, y = 2/3, yend = 2/3), colour = "grey", size = 0.25) +
  geom_segment(data = d1,
               x = 1999.5, xend = 2009.5, y = 0, yend = 0,
               colour = "grey", size = 0.25) +
  geom_point(data = d1,
             aes(x = year, y = arcade_revenue_scaled),
             colour = "#ba0f27") +
  geom_line(data = d1,
            aes(x = year, y = arcade_revenue_scaled),
              colour = "#ba0f27") +
  geom_point(data = d1,
             aes(x = year, y = doctorates_scaled),
             colour = "black") +
  geom_line(data = d1,
            aes(x = year, y = doctorates_scaled),
            colour = "black") +
  geom_text(data = d1,
            aes(x = year, y = -0.05, label = year),
            colour = "black", size = 10) +
  geom_text(data = d1,
            aes(x = year, y = 1.05, label = year),
            colour = "#ba0f27", size = 10) +
  geom_segment(data = d1,
               x = 1999.5, xend = 2009.5, y = 0, yend = 0,
               colour = "grey", size = 0.25) +
  geom_segment(data = d1,
               x = 1999.5, xend = 2009.5, y = 1, yend = 1,
               colour = "grey", size = 0.25) +
  geom_segment(data = axis_ticks,
               aes(x = x, xend = x,
                   y = y1, yend = y1 - 0.025),
               colour = "grey", size = 0.25) +
  geom_segment(data = axis_ticks,
               aes(x = x, xend = x,
                   y = y2, yend = y2 + 0.025),
               colour = "grey", size = 0.25) +
  annotate("text", x = 1999, y = 0, label = "$1 billion", colour = "#ba0f27", hjust = 1, size = 10) +
  annotate("text", x = 1999, y = 0.25, label = "$1.25 billion", colour = "#ba0f27", hjust = 1, size = 10) +
  annotate("text", x = 1999, y = 0.5, label = "$1.5 billion", colour = "#ba0f27", hjust = 1, size = 10) +
  annotate("text", x = 1999, y = 0.75, label = "$1.75 billion", colour = "#ba0f27", hjust = 1, size = 10) +
  annotate("text", x = 1999, y = 1, label = "$2 billion", colour = "#ba0f27", hjust = 1, size = 10) +
  annotate("text", x = 2010, y = 0, label = "500 degrees", colour = "black", hjust = 0, size = 10) +
  annotate("text", x = 2010, y = 1/3, label = "1000 degrees", colour = "black", hjust = 0, size = 10) +
  annotate("text", x = 2010, y = 2/3, label = "1500 degrees", colour = "black", hjust = 0, size = 10) +
  annotate("text", x = 2010, y = 1, label = "2000 degrees", colour = "black", hjust = 0, size = 10) +
  annotate("text", x = 2004.5, y = 1.5, label = "Total revenue generated by arcades", colour = "#ba0f27", hjust = 0.5, size = 25) +
  annotate("text", x = 2004.5, y = 1.4, label = "correlates with", colour = "grey", hjust = 0.5, size = 12) +
  annotate("text", x = 2004.5, y = 1.3, label = "Computer science doctorates awarded in the US", colour = "black", hjust = 0.5, size = 25) +
  annotate("text", x = 2004.5, y = 1.2, label = "Correlation: 98.51% (r=0.985065)", colour = "grey", hjust = 0.5, size = 10) +
  annotate("text", x = 1998, y = 0.5, label = "Arcade revenues", colour = "#ba0f27", hjust = 0, size = 8, angle = 90) +
  annotate("text", x = 2011, y = 0.5, label = "Computer science doctorates", colour = "black", hjust = 0.5, size = 8, angle = -90) +
  xlim(1998, 2011) +
  labs(caption = "Visualisation: Jonathan Kitt | Data source: www.tylervigen.com | #30DayChartChallenge 2022 | Day 13: correlation") +
  theme_void() +
  theme(panel.background = element_rect(fill = "white", colour = "white"),
        plot.background = element_rect(fill = "white", colour = "white"),
        axis.title = element_blank(),
        axis.text = element_blank(),
        plot.caption = element_text(colour = "black", hjust = 0.5, size = 25,
                                    margin = margin(b = 10)))

# Save plot ----

ggsave("2022/plots/finished/13_correlation.png", p, dpi = 320, width = 12, height = 6)